mods.extendedcrafting.TableCrafting.addShaped("creativerite_helmet", <item:upgradednetherite_creative:creative_upgraded_netherite_helmet>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);

mods.extendedcrafting.TableCrafting.addShaped("creativerite_chestplate", <item:upgradednetherite_creative:creative_upgraded_netherite_chestplate>, [
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>]
]);

mods.extendedcrafting.TableCrafting.addShaped("creativerite_leggings", <item:upgradednetherite_creative:creative_upgraded_netherite_leggings>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>]
]);

mods.extendedcrafting.TableCrafting.addShaped("creativerite_boots", <item:upgradednetherite_creative:creative_upgraded_netherite_boots>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>]
]);

mods.extendedcrafting.TableCrafting.addShaped("creativerite_horse_armor", <item:upgradednetherite_creative:creative_upgraded_netherite_horse_armor>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>], 
	[<item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:upgradednetherite_creative:creative_upgraded_netherite_ingot>, <item:minecraft:air>]
]);