mods.avaritia.ExtremeTableCrafting.addShaped("neutronium_panel",<item:solarflux:sp_avaritia.neutronium>, [
    [<item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>], 
	[<item:solarflux:photovoltaic_cell_6>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_pile>, <item:solarflux:photovoltaic_cell_6>], 
	[<item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>, <item:solarflux:photovoltaic_cell_6>], 
	[<item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>], 
	[<item:avaritia:neutron_nugget>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_nugget>], 
	[<item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_nugget>], 
	[<item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>], 
	[<item:solarflux:sp_8>, <item:avaritia:neutron_gear>, <item:avaritia:neutron_gear>, <item:avaritia:neutron_gear>, <item:avaritia:neutron_gear>, <item:avaritia:neutron_gear>, <item:avaritia:neutron_gear>, <item:avaritia:neutron_gear>, <item:solarflux:sp_8>], 
	[<item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>, <item:solarflux:sp_8>]
    ]);

mods.avaritia.ExtremeTableCrafting.addShaped("infinity_panel", <item:solarflux:sp_avaritia.infinity>, [
	[<item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>], 
	[<item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix_ingot>], 
	[<item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>], 
	[<item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>], 
	[<item:avaritia:infinity_catalyst>, <item:avaritia:infinity_nugget>, <item:avaritia:infinity_nugget>, <item:avaritia:infinity_nugget>, <item:avaritia:infinity_nugget>, <item:avaritia:infinity_nugget>, <item:avaritia:infinity_nugget>, <item:avaritia:infinity_nugget>, <item:avaritia:infinity_catalyst>], 
	[<item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_catalyst>], 
	[<item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>], 
	[<item:solarflux:sp_avaritia.neutronium>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:solarflux:sp_avaritia.neutronium>], 
	[<item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>, <item:solarflux:sp_avaritia.neutronium>]
]);